api/urls.py
from django.urls import path

from api import views
from api.views import BookReviewDetailAPIView, BookReviewListAPIView, BookDetailAPIView, BookListCreateAPIView

urlpatterns = [
    path('reviews/', BookReviewListAPIView.as_view(), name='reviews-list'),
    path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(),name='reviews-detail'),
    path('books/', BookListCreateAPIView.as_view(), name='books-list'),
    path('books/<int:id>/', BookDetailAPIView.as_view(), name='books-detail'),


]

books/urls.py
from django.urls import path

from books import views
from books.views import BookListView, BookDetailView, ReviewUpdateView

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('<int:book_id>/', BookDetailView.as_view(), name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('reviews/<int:pk>/edit/', ReviewUpdateView.as_view(), name='edit_review'),
    path('reviews/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

onfig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import landing_page, HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('landing/', landing_page, name = 'landing_page'),
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('api/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView,EditProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit', EditProfileView.as_view(), name='edit-profile'),

]

books/models.py
from users.models import CustomUser
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

class Book(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()    
    isbn = models.CharField(max_length=17)
    cover_picture = models.ImageField(default='cover_pictures/default-book.jpg', upload_to='cover_pictures')
    # created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title

class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    bio = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

class BookAuthor(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.author} - {self.book}'


class BookReview(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    comment = models.TextField()
    stars_given = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(5)])
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f'{self.stars_given} for {self.book} by {self.user}'

books/forms.py
from django import forms

from books.models import Book, BookReview

from users.models import CustomUser

class BookCreateForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ('title', 'description', 'isbn', 'cover_picture')


class BookReviewForm(forms.ModelForm):
    stars_given = forms.IntegerField(max_value=5, min_value=1)
    class Meta:
        model = BookReview
        fields = ['stars_given', 'comment']

books/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.shortcuts import render
from books.models import Book


from books.forms import BookCreateForm, BookReviewForm
from books.models import Book, BookReview


class BookListView(View):
    def get(self, request):
        books = Book.objects.all()
        search = request.GET.get('q')
        if search:
            books = books.filter(title__icontains=search)

        paginator = Paginator(books, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)

        context = {
                'page_obj': page_obj,
                'books': books,
            }

        return render(request, 'list.html', context)


class BookDetailView(View):
    def get(self, request, book_id):
        book = Book.objects.get(pk=book_id)
        form = BookReviewForm
        reviews = BookReview.objects.filter(book=book)[::-1]
        context = {
            'book': book,
            'reviews': reviews,
            'form': form,


        }
        return render(request, 'detail.html', context)

    def post(self, request, book_id):
        book = Book.objects.get(pk=book_id)
        form = BookReviewForm(request.POST)
        if form.is_valid():
            review = BookReview.objects.create(
                book=book,
                user=request.user,
                comment=form.cleaned_data['comment'],
                stars_given=form.cleaned_data['stars_given'],

            )

            review.save()
            return redirect('books:detail', book_id=book_id)
        context = {
            'form': form,
        }
        return render(request, 'detail.html', context)

class ReviewUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
        model = BookReview
        form_class = BookReviewForm
        template_name = 'edit_book_reviews.html'
        context_object_name = 'review'


        def form_valid(self, form):
            form.instance.user = self.request.user
            return super().form_valid(form)

        def get_success_url(self):
            return reverse_lazy('books:detail',
                                kwargs={'book_id': self.object.book.id})

        def test_func(self):
            review = self.get_object()
            return self.request.user == review.user
def edit_review(request, review_id):  
    review = get_object_or_404(BookReview, id=review_id, user=request.user)
    if request.method == "POST":
        form = BookReviewForm(request.POST, instance=review)
        if form.is_valid():
            form.save()
            return redirect('books:detail', book_id=review.book.id)
    else:
        form = BookReviewForm(instance=review)
    return render(request, 'edit_book_reviews.html', {'form': form})

def delete_review(request, review_id):
    review = get_object_or_404(BookReview, id=review_id, user=request.user)

    if request.method == "POST":
        review.delete()
        return redirect('books:detail', book_id=review.book.id)
    return render(request, 'delete_review.html', {'review': review})
def add_book (request):
    if request.method == 'POST':
        form = BookCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('books:list')
    else:
        form = BookCreateForm()
    return render(request, 'add_book.html', {'form': form})

books/templates/add_book.html
<!-- books/templates/books/add_book.html -->

{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add Book{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-3">
            <h2>Add books</h2>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-primary" >Kitob Qoshish</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

books/templates/delete_review.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{book.title}}{% endblock %}

{% block content %}


<h2>Delete Review</h2>

<form method="post">
<p> O'chirishga aminmisiz?</p>
    {% csrf_token %}

    <button type="submit">HA, O'chirilsin</button>
</form>
<a href="{% url 'books:detail' book_id=review.book.id %}"> Bekor qilish </a>
{% endblock content %}

books/templates/detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{book.title}}{% endblock %}

{% block content %}
    <div class="row" >
       <div class="col-2">
            <img style="width: 200px; height: 320;" src="{{book.cover_picture.url }}">
       </div>
       <div class="col-6" >
            <h4>{{ book.title }}</h4>
            <p>{{ book.description }}</p>
            <p>{{ book.isbn }}</p>
       </div>
`            <form action="{% url  'books:detail' book.id %}" method="post" >
`                {% csrf_token %}
                {{ form|crispy }}

                <button class="btn btn-primary" type="submit" > Add review </button>

            </form>
        {% if reviews %}
            <h3>Reviews</h3>
               <hr>
            {% for review in reviews %}
            <div class="row mb-3" >
                <div class="col-1">
                    <img style="width: 50px; height: 50px; border-radius:50%;" src="{{review.user.profile_picture.url}}">
                </div>
                <div class="col-7" >
                     {{ review.stars_given }} stars by  <b> {{ review.user.username }}</b>
                    {% if review.user == request.user %}
                        <a href="{% url 'books:edit_review' review.id %}"><i class="bi bi-pencil-square"></i></a>
                        <a href="{% url 'books:delete_review' review.id %}"><i class="bi bi-trash3"></i></a>
                    {% endif %}
                    <p>{{ review.comment }}</p>
                </div>
            {% endfor %}
        {% endif %}
       </div>
    </div>
{% endblock  %}

books/templates/edit_book_reviews.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title %}{{book.title}}{% endblock %}

{% block content %}
    <div class="row" >
         <h2>Edit reviews</h2>
       <div class="col-2">
            <img style="width: 200px; height: 320;" src="{{book.cover_picture.url }}">
       </div>
       <div class="col-6" >

            <h4>{{ book.title }}</h4>
            <p>{{ book.description }}</p>
            <p>{{ book.isbn }}</p>
       </div>
            <form action="" method="post" >
                {% csrf_token %}
                {{ form|crispy }}

                <button class="btn btn-primary" type="submit" >Save reviews </button>

            </form>
        {% if reviews %}
            <h3>Reviews</h3>
               <hr>
            {% for review in reviews %}
            <div class="row mb-3" >
                <div class="col-1">
                    <img style="width: 50px; height: 50px; border-radius:50%;" src="{{review.user.profile_picture.url}}">
                </div>
                <div class="col-7" >
                     {{ review.stars_given }} stars by  <b> {{ review.user.username }}</b>
                    <a href=""><i class="bi bi-pencil-square"></i> </a>  <a href=""><i class="bi bi-trash3"></i></a>
                    <p>{{ review.comment }}</p>
                </div>
            {% endfor %}
        {% endif %}
       </div>
    </div>
{% endblock  %}

books/templates/list.html
{% extends 'base.html' %}

{% block title %}Books{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <div class="row">
        <div class="container">
        <h1>Books</h1>
        {% for book in page_obj %}
            <div class="row mb-3">
                <div class="col-2">
                    <img style="width: 200px; height: 320;" src="{{ book.cover_picture.url }}">
                </div>
                <div class="col-6">
                    <a href="{% url 'books:detail' book.id %}">{{ book.title }}</a>
                    <p>{{ book.description }}</p>
                </div>
            </div>
        {% endfor %}
    </div>

    <!-- Bootstrap pagination -->
    <nav aria-label="Page navigation example">
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
            </a>
          </li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
          {% if page_obj.number == num %}
            <li class="page-item active">
              <a class="page-link">{{ num }}</a>
            </li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
          {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
            </a>
          </li>
        {% endif %}
      </ul>
    </nav>
 </div>
{% else %}
<div class="text-center" >
<h1> Log in bolganingizdan keyin kitoblarni korshingiz mumkun </h1>
<a class="btn btn-primary" href="{%url 'users:login'%}" >Login </a>
</div>
{% endif %}
{% endblock %}