api/urls.py
from django.urls import path

from api import views
from api.views import BookReviewDetailAPIView, BookReviewListAPIView, BookDetailAPIView, BookListCreateAPIView

urlpatterns = [
    path('reviews/', BookReviewListAPIView.as_view(), name='reviews-list'),
    path('reviews/<int:id>/', BookReviewDetailAPIView.as_view(),name='reviews-detail'),
    path('books/', BookListCreateAPIView.as_view(), name='books-list'),
    path('books/<int:id>/', BookDetailAPIView.as_view(), name='books-detail'),


]

books/urls.py
from django.urls import path

from books import views
from books.views import BookListView, BookDetailView, ReviewUpdateView

app_name = 'books'
urlpatterns = [
    path('', BookListView.as_view(), name='list'),
    path('<int:book_id>/', BookDetailView.as_view(), name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('reviews/<int:pk>/edit/', ReviewUpdateView.as_view(), name='edit_review'),
    path('reviews/<int:review_id>/edit/', views.edit_review, name='edit_review'),
    path('reviews/<int:review_id>/delete/', views.delete_review, name='delete_review'),
]

onfig/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from . import settings
from .views import landing_page, HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('landing/', landing_page, name = 'landing_page'),
    path('users/', include('users.urls'), name='users'),
    path('books/', include('books.urls'), name='books'),
    path('api/', include('api.urls'), name='api'),
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
]
    
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import RegisterView, LoginView, LogoutView, ProfileView,EditProfileView

app_name = 'users'

urlpatterns = [
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit', EditProfileView.as_view(), name='edit-profile'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" >
    <title>{% block title %} {%endblock title%}</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'landing_page' %}">Goodreads clone</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'books:list' %}">Books</a>
                </li>
             {%if user.is_superuser %}
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'books:add_book' %}">Add books</a>
                </li>
             {% endif %}
          </ul >

          <form class="d-flex me-2" role="search" action="{% url 'books:list' %}" >
            <input class="form-control me-2" type="search" placeholder="Qidiruv" aria-label="Search" name="q" >
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav me-5">
                 <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {{request.user.username}}
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'users:profile' %}">Profile</a></li>

                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item" href="{%url 'users:logout' %}">Logout</a></li>

             {% else %}
                      <a class="btn btn-primary me-5 " href="{% url 'users:login' %}">Login</a>
            {% endif %}
                  </ul>
                </li>
            </ul>
        </div>
      </div>
    </nav>

<div class="container" >

            {% block content %}



            {% endblock content %}

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

templates/home.html
{% extends 'base.html' %}
{% block title %} Home page {% endblock %}

{% block content %}
    <h2>Home page</h2>
    <div class="container posts-content">
        {% for review in page_obj %}
            <div class="row">
                <div class="col-lg-6">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="media mb-3">
                                <img style="width: 300px; height: 400px;" src="{{ review.book.cover_picture.url }}" alt="">
                                <div class="media-body ml-3">
                                    {{ review.user.username }}
                                    <p>{{ review.book.title }}</p>
                                    <p>{{ review.comment }}</p>
                                    <p>Rating: {{ review.stars_given }} / 5</p>
                                    <p>{{review.created_at}}</p>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="javascript:void(0)" class="d-inline-block text-muted">
                                <strong>123</strong> <small class="align-middle">Likes</small>
                            </a>
                            <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                                <strong>12</strong> <small class="align-middle">Comments</small>
                            </a>
                            <a href="javascript:void(0)" class="d-inline-block text-muted ml-3">
                                <small class="align-middle">Repost</small>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>


    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
            {% endif %}

            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <li class="page-item active">
                        <a class="page-link">{{ num }}</a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}

            {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

templates/landing_page.html
{% extends 'base.html' %}
{% block title %} Landing page {%endblock%}
<!--{% if messages %}-->
<!--    {% for message in messages %}-->
<!--        <span class="{{ message.tags }}">{{ message }}</span>-->
<!--    {% endfor %}-->
<!--{% endif %}-->



{% block content %}

    <h2>Landing page</h2>
<p>
    Goodreads is an American social cataloging website and a subsidiary of Amazon[1] that allows individuals to search its database of books, annotations, quotes, and reviews. Users can sign up and register books to generate library catalogs and reading lists. They can also create their own groups of book suggestions, surveys, polls, blogs, and discussions. The website's offices are located in San Francisco.[2]

Goodreads was founded in December 2006 and launched in January 2007 by Otis Chandler and Elizabeth Khuri Chandler.[3][4] In December 2007, the site had 650,000 members[5] and 10,000,000 books had been added.[6] By July 2012, the site reported 10 million members, 20 million monthly visits, and thirty employees.[7] On March 28, 2013, Amazon announced its acquisition of Goodreads,[8] and by July 23, 2013, Goodreads announced their user base had grown to 20 million members.[9]

By September 2023, the site had more than 150 million members.[10]
</p>
{% endblock content %}